name: Profile Readme Snake

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-snake:
    name: Update Snake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=orange
            dist/github-snake-dark.svg?palette=github-dark&color_snake=orange

      - name: Commit and push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add dist/
          git commit -m "Update snake animation" || exit 0
          git push
